[package]
name = 'lake-token'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/panoptisDev/APTOS_token_contract.git'
rev = 'conversions'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
admin = '153ba9a4472af03957094fe6e7c97e0257359a1649129331ad6c07ecb2d9ccd5'
